format = """$directory$git_branch$git_status$python$nodejs$rust$character"""

[directory]
truncation_length = 3

[git_branch]
format = "[$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[python]
format = '[py $version]($style) '

[nodejs]
format = '[node $version]($style) '

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
